### ISSUE TITLE
Warning about a possible event emitter leak when a lot of clusters is spawned

### ISSUE THREAD

**Issue by Deivu** [Deivu/Indomitable#6]
```js
WARN [Sat,06/29/24,11:39:10] ([Manager (4139165)]): MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
    at [kNewListener] (node:internal/event_target:520:17)
    at [kNewListener] (node:internal/abort_controller:238:24)
    at EventTarget.addEventListener (node:internal/event_target:629:23)
    at MainWorker.waitForPromise (file:///home/kashima/bot/prod/node_modules/indomitable/dist/index.mjs:234:25)
    at file:///home/kashima/bot/prod/node_modules/indomitable/dist/index.mjs:200:12
    at new Promise (<anonymous>)
    at MainWorker.send (file:///home/kashima/bot/prod/node_modules/indomitable/dist/index.mjs:184:12)
    at file:///home/kashima/bot/prod/node_modules/indomitable/dist/index.mjs:1087:98
    at Array.map (<anonymous>)
    at KashimaManager.broadcast (file:///home/kashima/bot/prod/node_modules/indomitable/dist/index.mjs:1087:69)
```

This is most likely not a real leak, and probably would just need a increased listener count limit, will monitor this issue for the meantime.

**Comment by Deivu** [comment]
Fixed since d72e236
